### ISSUE TITLE
Rename Index

### ISSUE THREAD

**Issue by lolmaus** [empress/field-guide#26]
The Index page and the `index.md` file seem to be hardcoded.

Renaming `index.md` crashes the app with:

```
FetchError: invalid json response body at http://localhost:4200/docs/index.json reason: Unexpected token < in JSON at position 0
    at /path/to/addon/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

"Index" means an alphabetical list, a table of contents.

But the Index page typically contains an introduction to the addon and has no alphabetical lists.

I would like to be able to rename it.

PS If you agree with this and think this is "a good starting issue", please provide some guidelines, and I'll be happy to attempt a PR.

**Comment by mansona** [comment]
hey @lolmaus 👋 thanks for opening these issues! it's really helping me push forward with field-guide 🎉 

This particular issue is unlikely going to be fixed/changed though 🤔 index.md is intended to be similar to index.html as in "the default thing to serve when you access this folder"

This is a behaviour that is very well documented in a lot of hosting implementations and is even baked into node packages, so I'm pretty confident that this is an industry standard. I know we've had extensive conversations on the Discord about being able to configure and change things but adding the ability to change something so fundamental like this will likely introduce significant complexity for very little gain.

Does this all make sense?

**Comment by lolmaus** [comment]
I don't mind having the file named `index.md`.

But I don't like the navigation menu entry to be called `Index` for the end user. I want to rename it to something more user-friendly, such as `Intro` or `About`.

PS Note how the zero-config doctrine creates a conflict: you want the file name to indicate "the default thing to serve when you access this folder". I want the menu entry to be human-friendly. If `field-guide` were more flexible (e. g. this particular case could be solved with Markdown Frontmatter), then the issue wouldn't exist.

PPS This situation reminds me of desktop apps naming their menu entries as `File`, `Edit`, `View`. These names came from ancient file managers and were heavily related to manipulating files. Now every other app has a `File` entry, even when it's not dealing with files. Maybe it's time to move on?

![image](https://user-images.githubusercontent.com/200884/85393437-ab5bf700-b555-11ea-89aa-12e0e0100e7e.png)
